import "@/styles/globals.css";

import { GeistSans } from "geist/font/sans";

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${GeistSans.variable} bg-black text-white`}>
      <body className="p-4 flex flex-col gap-4">
        <header className="flex justify-between gap-4">
          <h1>Gallery</h1>
          <p>Sign in</p>
        </header>
        {children}
      </body>
    </html>
  );
}
