import { ClerkProvider } from "@clerk/nextjs";
import type { PropsWithChildren } from "react";
import { GeistSans } from "geist/font/sans";

import TopNav from "./_components/TopNav";

import "@/styles/globals.css";

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout(props: PropsWithChildren) {
  const { children } = props;

  return (
    <ClerkProvider>
      <html lang="en" className={`${GeistSans.variable} bg-black text-white`}>
        <body className="p-4 flex flex-col gap-4">
          <TopNav />
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
